### ISSUE TITLE
the weather in the world

### ISSUE THREAD

**Issue by yixiaaaaa** [Irgendwer01/PersonalWorlds#11]
The weather in the world will change with the change of the main world, even if the weather change is canceled in the UI, this phenomenon does not seem to appear in the original version, it is very distressing for me to play the industrial modpack, it often affects the line of sight, and the weather is invalid with the command in the dimension, and it needs to go back to the main world setting to take effect. I would appreciate it if you could fix it

**Comment by Irgendwer01** [comment]
fixed in #12
